Kerberos AES: Encode password as UTF-8
Using getKerberosTGT with a password that has non-latin-1 characters fails with

  UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-127: ordinal not in range(256)

As string_to_key from _RC4 expects a string (calls encode), string_to_key for AES should expect the same and do proper UTF-8 encoding as per MS-KILE.